---
abstract: 'Simple iterator with lookahead and unget'
author:
  - 'Paulo Custodio <pscust@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Iterator-Simple-Lookahead
no_index:
  directory:
    - t
    - inc
requires:
  Class::XSAccessor::Array: 1.08
  Iterator::Simple: 0.06
  Test::More: 0.98
version: 0.01
